# File: backend/app/db/migrations/script.py.mako
# Version: v0.1.0
"""add primers tables

Revision ID: 4f130a5cb1f6
Revises: 0002_add_ga_progress_to_designs
Create Date: 2025-10-22 17:26:47.221651

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f130a5cb1f6'
down_revision = '0002_add_ga_progress_to_designs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('report_url', sa.String(length=512), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('sequence_len', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_runs_job_id')
    )
    op.create_index(op.f('ix_runs_job_id'), 'runs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_job_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
