# File: backend/app/core/jobs/runner.py
# Version: v0.7.0
"""
Async job runner (SSE-enabled) that runs the CornStructor pipeline **in-process**.

Changes in v0.7.0:
- Replaces external CLI with a native pipeline (backend.app.core.pipeline.py_runner.execute_pipeline)
- Streams meaningful progress messages to SSE
- Persists tree.json into Design (if linked) and sets Run.status/report_url/exit_code
- Guarantees a non-404 report (index.html is generated by run_index)
"""
from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Dict, Optional

from backend.app.core.config import settings
from backend.app.core.pipeline.py_runner import execute_pipeline

from backend.app.db.session import SessionLocal
from backend.app.services.design_store import attach_tree_to_design, mark_run_completed


class Job:
    """In-memory job handle storing output directory and SSE queue."""
    def __init__(self, job_id: str, outdir: Path, queue: asyncio.Queue[str]):
        self.job_id = job_id
        self.outdir = outdir
        self.queue = queue
        self.task: Optional[asyncio.Task] = None


class JobManager:
    def __init__(self) -> None:
        self._jobs: Dict[str, Job] = {}

    def reserve_job_id(self) -> str:
        """Reserve a job id and prepare its output directory."""
        import uuid

        job_id = uuid.uuid4().hex[:12]
        outdir = Path(settings.OUTPUT_DIR) / job_id
        outdir.mkdir(parents=True, exist_ok=True)
        self._jobs[job_id] = Job(job_id=job_id, outdir=outdir, queue=asyncio.Queue())
        return job_id

    def get(self, job_id: str) -> Optional[Job]:
        return self._jobs.get(job_id)

    async def start_with_existing_id(self, *, job_id: str, fasta_text: str) -> None:
        """Launch the in-process pipeline for a reserved job id."""
        job = self._jobs.get(job_id)
        if not job:
            job_id = self.reserve_job_id()
            job = self._jobs[job_id]

        loop = asyncio.get_running_loop()

        def emit(msg: str) -> None:
            # thread-safe push to SSE queue from worker thread
            loop.call_soon_threadsafe(job.queue.put_nowait, msg)

        async def _runner(j: Job, fasta_text: str):
            try:
                # Run the heavy pipeline on a thread so we don't block the event loop
                rc = await asyncio.to_thread(
                    execute_pipeline,
                    outdir=j.outdir,
                    fasta_text=fasta_text,
                    job_id=j.job_id,
                    levels_path=settings.LEVELS_PATH,
                    globals_path=settings.GLOBALS_PATH,
                    reports_public_base=settings.REPORTS_PUBLIC_BASE,
                    emit_log=emit,
                )

                # Persist tree.json into the Design (if a Design is linked to this Run)
                tree_path = j.outdir / "tree.json"
                if tree_path.exists():
                    try:
                        tree_text = tree_path.read_text(encoding="utf-8")
                        db = SessionLocal()
                        try:
                            attach_tree_to_design(db, job_id=j.job_id, tree_json=tree_text)
                            await j.queue.put("Stored design tree in database")
                        finally:
                            db.close()
                    except Exception as ex:
                        await j.queue.put(f"WARN: failed to store tree.json: {ex}")

                # Report URL always exists (run_index writes index.html)
                report_url = f"{settings.REPORTS_PUBLIC_BASE}/{j.job_id}/index.html"
                await j.queue.put(f"RESULT: {report_url}")
                await j.queue.put(f"EXIT: {rc}")

                # Update Run row
                try:
                    db = SessionLocal()
                    try:
                        mark_run_completed(db, job_id=j.job_id, report_url=report_url, exit_code=rc)
                    finally:
                        db.close()
                except Exception as ex:
                    await j.queue.put(f"WARN: failed to update Run status: {ex}")

            finally:
                await j.queue.put("__EOF__")

        job.task = asyncio.create_task(_runner(job, fasta_text))


# Singleton instance
job_manager = JobManager()
